name: 'Setup Homebrew OpenSSL'
description: 'Installs and configures Homebrew OpenSSL and persists environment variables'
inputs:
  version:
    description: 'The version of OpenSSL to install (default: openssl@3)'
    default: 'openssl@3'
runs:
  using: 'bash'
  main: './setup-openssl.sh'

